### PR TITLE
Add HTTPS `rejectUnauthorized` option

### PR DESCRIPTION
**Pull request by spinda**
# Description

This allows for connecting to cameras with self-signed certificates over HTTPS.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by spinda** [comment]
Oops, I just discovered this is already possible via the `agent` option. Closing.

**Comment by FantasticFiasco** [comment]
Hi @spinda! Out of curiosity, how did you accomplish this using the `agent` option? And what cameras support Sigv4?

**Comment by spinda** [comment]
Hi @FantasticFiasco! Like this:

```typescript
new Connection(
  Protocol.Https,
  host,
  port,
  username,
  password,
  {
    agent: new HttpsAgent({
      rejectUnauthorized: false,
    }),
  },
);
```

**Comment by FantasticFiasco** [comment]
Nice, thanks!

**Comment by FantasticFiasco** [comment]
With the upcoming migration from [got](https://github.com/sindresorhus/got) to [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch), the following [issue](https://github.com/orgs/nodejs/discussions/44038) is showing us how to accept invalid certificates using `fetch`.

**Pull request closed without merging**
